global:
  scrape_interval: 1m

scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 1m
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'go-event-service'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8000' ]
