app:
  kafka:
    brokers:
     - localhost:19092
    consumer-group: go-event-service
    topic: events

  elastic:
    addresses:
      - http://localhost:9200
    user: elastic
    password: password
    events-index: events
